export const rovers = [
  {
    name: "Curiosity",
    value: "curiosity",
    model: "https://mars.nasa.gov/gltf_embed/24584",
    isActive: true,
    launchDate: "2011-11-26",
    landingDate: "2012-08-06",
    landingSite: "Gale Crater",
    maxSol: "3993 and counting",
  },
  {
    name: "Opportunity",
    value: "opportunity",
    model: "https://mars.nasa.gov/gltf_embed/24883",
    isActive: false,
    launchDate: "2003-07-07",
    landingDate: "2004-01-25",
    landingSite: "Meridiani Planum",
    maxSol: "5111",
  },
  {
    name: "Spirit",
    value: "spirit",
    model: "https://mars.nasa.gov/gltf_embed/24883",
    isActive: false,
    launchDate: "2011-11-26",
    landingDate: "2012-08-06",
    landingSite: "Gusev Crater",
    maxSol: "2208",
  },
];
export const roverCameras = [
  {
    id: 0,
    value: "ALL",
    name: "All Cameras",
    rover: ["curiosity", "opportunity", "spirit"],
  },
  {
    id: 1,
    value: "FHAZ",
    name: "Front Hazard Avoidance Camera",
    rover: ["curiosity", "opportunity", "spirit"],
  },
  {
    id: 2,
    value: "RHAZ",
    name: "Rear Hazard Avoidance Camera",
    rover: ["curiosity", "opportunity", "spirit"],
  },
  {
    id: 3,
    value: "MAST",
    name: "Mast Camera",
    rover: ["curiosity"],
  },
  {
    id: 4,
    value: "CHEMCAM",
    name: "Chemistry and Camera Complex",
    rover: ["curiosity"],
  },
  {
    id: 5,
    value: "MAHLI",
    name: "Mars Hand Lens Imager",
    rover: ["curiosity"],
  },
  { id: 6, value: "MARDI", name: "Mars Descent Imager", rover: ["curiosity"] },
  {
    id: 7,
    value: "NAVCAM",
    name: "Navigation Camera",
    rover: ["curiosity", "opportunity", "spirit"],
  },
  {
    id: 8,
    value: "PANCAM",
    name: "Panoramic Camera",
    rover: ["opportunity", "spirit"],
  },
  {
    id: 9,
    value: "MINITES",
    name: "Miniature Thermal Emission Spectrometer",
    rover: ["opportunity", "spirit"],
  },
];
