import "./globals.css";

// React bootstrap
import "bootstrap/dist/css/bootstrap.min.css";

// React datepicker
import "react-datepicker/dist/react-datepicker.css";

import CosmicNavbar from "@/components/ui/navbar";

export const metadata = {
  title: "Cosmic Ocean | The absence of evidence is not evidence of absence.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CosmicNavbar />
        {/*  */}
        <main>{children}</main>
      </body>
    </html>
  );
}
